# file_version: {{ pkg_hash }}
# citer_version: {{ citer_version }}
# DO NOT EDIT THIS BY HAND!
# This document was automatically generated by the `citer` package.
# tools::md5sum()

# Citer Environment Setup
citation_on_load <- function() {

  pkg_name <- "{{ pkg_name }}"
  
  packageStartupMessage(
    "Thank you for using ", pkg_name, "! ",
    "Please consider citing it in your work.\n",
    "You can find the citation information by running\n  citation(\"",
    pkg_name,
    "\")"
  )

}
