# file_version: d600ee038e855601248228fb12136e7d
# DO NOT EDIT THIS BY HAND!
# This document was automatically generated by the `citer` package.

# Citer Environment Setup
citation_on_load <- function() {

  pkg_name <- "citer"

  message("Thank you for using ", pkg_name, "!")
  message("Please consider citing it in your work. ", appendLF = FALSE)
  message(
    "You can find the citation information by running `citation('",
    pkg_name,
    "')`:"
  )

  citation(package = pkg_name)

}
