# file_version: 035b9a7e3195f093255d2e95bf6b3fd0
# DO NOT EDIT THIS BY HAND!
# This document was automatically generated by the `citer` package.
# tools::md5sum()

#' Citer Environment Setup
citation_on_load <- function() {

  pkg_name <- "citer"
  
  message("Thank you for using ", pkg_name, "!")
  message("Please consider citing it in your work. ", appendLF = FALSE)
  message(
    "You can find the citation information by running `citation('",
    pkg_name,
    "')`:"
  )

  citation(package = pkg_name)

}
